name: Docker CI

on: 
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
jobs:

  appVersion:
    runs-on: ubuntu-latest
    outputs:
      version_number: ${{ steps.vars.outputs.version_number }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      
    - name: set-output
      id: vars
      run: |
        version_number=$(sed -n 's/.*<p>\(.*\)<\/p>.*/\1/p' index.html)
        echo "version_number=${version_number}" >> "$GITHUB_OUTPUT"
      shell: bash

  dockerCI:
    name: dockerCI
    needs: appVersion
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      
      - name: Qemu installation
        uses: docker/setup-qemu-action@v3
        
      - name: Installation of Buildx image building engine
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: szymonmik/zad2-img:${{ needs.appVersion.outputs.version_number}}
          platforms: linux/amd64,linux/arm64
          
  kubernetesCI:
    name: kubernetesCI
    needs: [appVersion, dockerCI]
    runs-on: ubuntu-latest
    steps: 
      - name: Check out config-repo
        uses: actions/checkout@master
        with:
          repository: szymonmik/config-repo
          token: ${{ secrets.PAT_GITHUB }}
          
      - name: Edit deployment
        run: |
          git config --global user.name "ci"
          git config --global user.email "ci@ci.ci"
          git add deployment.yaml
          git commit -m "update app to version ${{ needs.appVersion.outputs.version_number }}"
          git push origin main